# Fukict Packages Build Configuration
# 包构建配置，定义每个包的构建参数

packages:
  # 浏览器环境包
  runtime:
    platform: browser
    entry: ['src/index.ts']
    format: esm
    description: '轻量级 VNode 到 DOM 渲染引擎'

  widget:
    platform: browser
    entry: ['src/index.ts']
    format: esm
    description: '组件编码范式抽象层'

  router:
    platform: browser
    entry: ['src/index.ts']
    format: esm
    description: '轻量级路由系统'

  # Node.js 环境包
  babel-plugin:
    platform: node
    entry: 'src/index.ts'
    format: ['esm', 'cjs']
    description: 'JSX 编译时转换插件'

  babel-preset-widget:
    platform: node
    entry: 'src/index.ts'
    format: ['esm', 'cjs']
    description: 'Widget 零配置预设'

# 通用构建配置
common:
  outDir: dist
  dts: true
  unbundle: true
  sourcemap: true
  splitting: false

  # 外部化依赖
  external:
    - '../types/'
    - '@fukict/'
    - '@babel/'
