/**
 * Package metadata
 * Auto-generated by scripts/extract-metadata.ts
 * DO NOT EDIT MANUALLY
 */

export const METADATA = {
  version: '0.0.0-alpha-20250608081318',
  name: '@fukict/widget',
  dependencies: {
    '@fukict/runtime': 'workspace:*',
  },
} as const;
