/**
 * Package metadata
 * Auto-generated by extract-metadata.ts - DO NOT EDIT MANUALLY
 */

export const METADATA = {
  name: '@fukict/basic',
  version: '0.1.0',
  description: 'Lightweight DOM rendering basic with extension mechanism',
  author: 'Fukict Team',
  license: 'MIT',
  homepage: '',
  repository: 'https://github.com/fukict/fukict.git',
} as const;
