/**
 * Package metadata
 * Auto-generated by extract-metadata.ts - DO NOT EDIT MANUALLY
 */

export const METADATA = {
  name: '@fukict/fetch',
  version: '0.1.11',
  description:
    'Axios-style HTTP client built on native fetch for Fukict framework',
  author: 'Fukict Team',
  license: 'MIT',
  homepage: '',
  repository: 'https://github.com/fukict/fukict.git',
} as const;
