/**
 * Package metadata
 * Auto-generated by extract-metadata.ts - DO NOT EDIT MANUALLY
 */

export const METADATA = {
  name: '@fukict/i18n',
  version: '0.1.7',
  description: 'Type-safe internationalization library for Fukict framework',
  author: 'Fukict Team',
  license: 'MIT',
  homepage: '',
  repository: 'https://github.com/fukict/fukict.git',
} as const;
